### ISSUE TITLE
My recent changes

### ISSUE THREAD

**Issue by curiousdannii** [0branch/hugo-unix#1]
Just letting you all know about my recent changes.

I've pulled in the branches I had gathered at https://github.com/curiousdannii/hugo. I've merged in the changes from garglk so that we now have the Glk source in this repository. I've left the v3.2 and hugor branches as is. I think the changes from hugor have probably already been incorporated, in which case we can delete that branch. (Edit: it's deleted.) I'm now going to mark my repository as archived. Long live hugo-unix!

I've added guard calls to `glk_stream_open_file` to avoid the common interpreter behaviour (but wrong according to the spec) of throwing a fatal error when reading a non-existent file.

I've increased MAXUNDO if not set because this seemed to be required for some larger games like Cryptozookeeper.

**Comment by realnc** [comment]
Thanks!

The hugor branch can indeed be removed. There's nothing of interest there whatsoever.
