### ISSUE TITLE
Move to the hugoif organisation?

### ISSUE THREAD

**Issue by curiousdannii** [0branch/hugo-unix#3]
@juhana started an organisation for Hugo: @hugoif.

We could move this repository there?

Could also consider just renaming it to "hugo" if you'd be happy allowing for other OSes ports to be included too?

**Comment by 0branch** [comment]
Sounds like a good idea. No objections to other ports being included either but I'd defer to those actively developing Hugo.

**Comment by realnc** [comment]
Sure.

**Comment by curiousdannii** [comment]
Sounds like most people are on board! :)

@0branch You should be able to transfer it from the settings page. @juhana may then have to accept the transfer.

**Comment by 0branch** [comment]
I'll give it a go now.

Edit: looks like I need the ability to create repositories in @hugoif first.

**Comment by juhana** [comment]
I sent y'all invitations to the group.

(CC @roodyyogurt & @robbsherwin)

**Comment by 0branch** [comment]
Transferred!

**Comment by roodyyogurt** [comment]
Great news.  I was hoping for something like this.
